### ISSUE TITLE
The piece returned by .move() method should be case sensitive

### ISSUE THREAD

**Issue by ammarCanc** [lengyanyu258/xiangqi.js#10]
There are some methods that returns `piece` such as history, redo, undo and move. This `piece` is always in lower case and it makes the move ambiguous (like considering `RED`'s move as `BLACK`'s). If we can convert `RED`'s move to upper case then it will be more readable.

**Comment by lengyanyu258** [comment]
When you use `move()`, `undo()` and `redo()`, there is `color` property to disambiguate the `piece` move.
```js
> xiangqi.redo()
{
  color: 'r',
  from: 'e3',
  to: 'e4',  
  flags: 'n',
  piece: 'p',
  iccs: 'e3e4'
}
> xiangqi.move('e6e5');
{
  color: 'b',
  from: 'e6',
  to: 'e5',
  flags: 'n',
  piece: 'p',
  iccs: 'e6e5'
}
```
Do we really need the upper case?

**Comment by ammarCanc** [comment]
Although the `color` is here for move conversion, I think it would be better to send `piece` in its actual notation.
As the FEN is having `RED`'s pieces in upper case, it would be better to return `RED` piece in upper case.
