### ISSUE TITLE
After we undo() a move, then how do we redo move() again?

### ISSUE THREAD

**Issue by nghiatruong** [lengyanyu258/xiangqi.js#3]
I use this to load a pgn file to view a whole game, with next and back button, I use back button with undo(), it worked well, but dont know how is best way to next move on pgn.

**Comment by lengyanyu258** [comment]
When you use undo(), you can get the last move object including ICCS, you can store the ICCS string locally and use it for move() later.
I will add redo() feature in the future. Be patient...

**Comment by lengyanyu258** [comment]
looks like the work is done, have fun!

**Comment by nghiatruong** [comment]
When I redo() some move which have seeds eat together, the fen will be wrong. You can try play from start, eat some. The seeds which was eaten will appear somewhere on the board. You can see video here https://drive.google.com/file/d/1-2ycJAh0Slxmy_3VizXIikz8TmPFCc3C/view?usp=sharing

**Comment by lengyanyu258** [comment]
> When I redo() some move which have seeds eat together, the fen will be wrong. You can try play from start, eat some. The seeds which was eaten will appear somewhere on the board. You can see video here https://drive.google.com/file/d/1-2ycJAh0Slxmy_3VizXIikz8TmPFCc3C/view?usp=sharing

It seems to be fixed.
