### ISSUE TITLE
Wrong error message shown while validating the FEN.

### ISSUE THREAD

**Issue by ammarCanc** [lengyanyu258/xiangqi.js#7]
As described in [Forsyth–Edwards Notation (FEN)](https://en.wikipedia.org/wiki/Forsyth–Edwards_Notation), black pieces are represented in lowercase and Red/White pieces are represented in uppercase.

I used validate_fen() method to check the validity of a FEN which is incorrect. The FEN is `4k4/9/9/9/9/9/9/c8/9/R2B1K3 r - - 0 1`, here red bishop is at wrong position while the error message I got is `1st field (piece positions) is invalid [black bishop should at right position].` Same is the case for Adviser and Pawn.

Actually the issue, as far as my knowledge, is that your code shows wrong color error.

<img width="635" alt="Screenshot 2022-09-30 at 1 36 07 PM" src="https://user-images.githubusercontent.com/81680225/193228801-d70d93c0-a329-4376-bf34-50d2f756a3d4.png">

**Comment by lengyanyu258** [comment]
Big thanks to you!

**Comment by ammarCanc** [comment]
@lengyanyu258 my pleasure.
